### ISSUE TITLE
Chinese Characters inserted into first line of Text exports.

### ISSUE THREAD

**Issue by adamraetz** [HalitTalha/mat-table-extensions#26]
`뿃뻃Date	Name	Phone	Type	`

Apologies if the characters are not Chinese.  However its tedious to constantly remove them every export. 

Thanks much.

**Comment by HalitTalha** [comment]
Thanks for reporting. I can't believe I haven't realized it for so long :)
Actually, Xlsx is employed for also txt exporting. I will check what's going wrong.

**Comment by HalitTalha** [comment]
Removed sheetjs from txt exporting implementation since this seems to be a known encoding issue with it.
Fix is ready for newly created ng6-7 branch for which I made a release under ng67 tag in npm. Soon this fix will be available for also the master branch which will be for Angular's latest stable version. After pushing it to master I will close this issue.

**Comment by HalitTalha** [comment]
Fix is available with the new release.
